apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kittisuw/gitops-argocd.git
    targetRevision: HEAD
    path: app-config/overlays/development
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
